### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by BravoHotshot** [NayanPahuja/lurc#3]
On running `make`, i am met with the error

/home/bravohotshot/lurc/http_client.cpp: In member function ‘bool HttpClient::verifySSLCert(SSL*, const std::string&)’:
/home/bravohotshot/lurc/http_client.cpp:81:18: error: ‘X509_check_host’ was not declared in this scope; did you mean ‘X509_check_trust’?
 81 |     int result = X509_check_host(cert,hostname.c_str(), hostname.length(),0,nullptr);
      |                  ^~~~~~~~~~~~~~~
      |                  X509_check_trust
make[2]: *** [CMakeFiles/lurc.dir/build.make:104: CMakeFiles/lurc.dir/http_client.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/lurc.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

My OpenSSL version is `3.0.14 4 Jun 2024`
My Doxygen version is `1.9.4-4`

**Comment by NayanPahuja** [comment]
Checking into it

**Comment by NayanPahuja** [comment]
**Fixed**
The error must be arising due to linking of libraries due to mismatch in OpenSSL version.
The latest patch should fix it!
